language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

matrix:
  allow_failures:
    - python: "pypy"

  fast_finish: true

install:
  - pip install -e .

script:
  - python -m unittest discover -v
